name: liga_shin_test
description: Test project of Liga Shin
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.3+4

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.4.0
  ionicons: ^0.2.2
  flutter_svg: ^1.1.6
  yandex_mapkit: ^3.3.3
  geolocator: ^9.0.2
  url_launcher: ^6.1.12
  maps_launcher: ^2.2.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  http: ^1.1.0
  intl: ^0.18.1
  get_it: ^7.6.0
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat-Medium.ttf
    - family: Source Sans Pro
      fonts:
        - asset: lib/assets/fonts/SourceSansPro-SemiBold.ttf
flutter_native_splash:
  android: true
  ios: true
  color: "FEFF01"
  image: "lib/assets/logo_liga.png"
  branding: "lib/assets/branding.png"
  android_12:
    image: "lib/assets/logo_liga12.png"
    color: "FEFF01"
    image_dark: "lib/assets/logo_liga12.png"
    color_dark: "FEFF01"
    branding: "lib/assets/branding12.png"

